### ISSUE TITLE
Něco špatně viz log

### ISSUE THREAD

**Issue by JiriKursky** [JiriKursky/Hass.io_CZ_SK_custom_components#5]
2019-06-15 12:59:31 INFO (MainThread) [root] AFSAPI Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/afsapi/__init__.py", line 101, in call
    self.__webfsapi = yield from self.get_fsapi_endpoint()
  File "/usr/local/lib/python3.7/site-packages/afsapi/__init__.py", line 81, in get_fsapi_endpoint
    endpoint = yield from self.__session.get(self.fsapi_device_url, timeout = self.timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 575, in _request
    break
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

**Comment by JiriKursky** [comment]
platform: google_maps :( uff
